const graphicsCards = [
    {
        id: 1,
        name: 'Nvidia GeForce RTX 3090',
        pciEvers: 'PCI Express 4.0 x16',
        price: 1499.99,
        memory: '24 GB',
        memoryType: 'GDDR6X',
    },
    {
        id: 2,
        name: 'AMD Radeon RX 6900 XT',
        pciEvers: 'PCI Express 4.0 x16',
        price: 999.99,
        memory: '16 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 3,
        name: 'Nvidia GeForce RTX 3080',
        pciEvers: 'PCI Express 4.0 x16',
        price: 799.99,
        memory: '10 GB',
        memoryType: 'GDDR6X',
    },
    {
        id: 4,
        name: 'AMD Radeon RX 6800 XT',
        pciEvers: 'PCI Express 4.0 x16',
        price: 649.99,
        memory: '16 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 5,
        name: 'Nvidia GeForce RTX 3070',
        pciEvers: 'PCI Express 4.0 x16',
        price: 499.99,
        memory: '8 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 6,
        name: 'AMD Radeon RX 6700 XT',
        pciEvers: 'PCI Express 4.0 x16',
        price: 479.99,
        memory: '12 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 7,
        name: 'Nvidia GeForce RTX 3060 Ti',
        pciEvers: 'PCI Express 4.0 x16',
        price: 399.99,
        memory: '8 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 8,
        name: 'AMD Radeon RX 6600 XT',
        pciEvers: 'PCI Express 4.0 x16',
        price: 379.99,
        memory: '8 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 9,
        name: 'Nvidia GeForce RTX 3060',
        pciEvers: 'PCI Express 4.0 x16',
        price: 329.99,
        memory: '12 GB',
        memoryType: 'GDDR6',
    },
    {
        id: 10,
        name: 'AMD Radeon RX 6600',
        pciEvers: 'PCI Express 4.0 x8',
        price: 299.99,
        memory: '8 GB',
        memoryType: 'GDDR6',
    },
];



